### ISSUE TITLE
English Version 和官方word版格式存在的一些问题

### ISSUE THREAD

**Issue by jqc25z** [sjtug/SJTUThesis#1010] opened 2024-02-03 03:16 UTC
1.目录中的格式差异：1.word版中目录的内容大写，且首字母大一号；2.word版中为Chapter One，Two...latex版中是Chapter1，2...；3.latex版中为bibliography，word版中为References；4.latex版中为List of Research Achievements，word版中为RESEARCH PROJECTS AND PUBLICATIONS DURING UNDERGRADUATE PERIOD
latex版目录：
![1706929944585](https://github.com/sjtug/SJTUThesis/assets/112072840/3db5ff72-7310-4622-bc6f-393e2bb551f3)
官方word版目录：
![1706930035178](https://github.com/sjtug/SJTUThesis/assets/112072840/267c7083-1e8f-42ea-a480-7f4233f3c2b2)
![1706930052028](https://github.com/sjtug/SJTUThesis/assets/112072840/55e9c5c6-64c4-41b6-9e63-d26e2829c38e)
2.正文标题，word版中为Chapter One，Two...latex版中是Chapter1，2...
latex版标题：
![1706930119828(1)](https://github.com/sjtug/SJTUThesis/assets/112072840/161fabef-3637-4adf-8942-4c2b037c6b5f)
官方word版标题：
![1706930153982(1)](https://github.com/sjtug/SJTUThesis/assets/112072840/cd0ea27d-a7ae-44d4-9fdc-c0588090c94b)
3.latex版中为bibliography，word版中为References；
4.latex版中为List of Research Achievements，word版中为RESEARCH PROJECTS AND PUBLICATIONS DURING UNDERGRADUATE PERIOD

**Comment by AlexaraWu** [comment] 2024-02-03 12:36
Duplicate of #913

**Closed as completed by AlexaraWu** 2024-02-03 12:36 UTC
